{{- if not .Values.auth.existingSecret }}
{{- if not .Values.auth.password }}
{{- fail "db.auth.password is required when db.enabled is true and no existingSecret is provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
