{{- if not .Values.app.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ignis.fullname" . }}-api
  labels:
    {{- include "ignis.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  StoreSettings__ConnectionString: {{ .Values.app.api.externalMongodbConnectionString | quote }}
{{- end }}
