apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.api.fullname" . }}
  labels:
    {{- include "app.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.api.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
      containers:
        - name: ignis-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: SparkSettings__Endpoint
              value: {{ .Values.api.sparkSettings.endpoint | quote }}
            - name: SparkSettings__FhirRelease
              value: {{ .Values.api.sparkSettings.fhirRelease | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.existingSecret | default (include "app.api.fullname" .) }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
