{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "app.api.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
  {{- if .Values.gateway.hostname }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /fhir
      backendRefs:
        - name: {{ include "app.api.fullname" . }}
          port: 8080
{{- end }}
